# Generated by Django 3.1.1 on 2020-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200929_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60, verbose_name='город')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.CharField(max_length=60, verbose_name='эл.почта')),
                ('address', models.CharField(max_length=60, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
    ]
