# Generated by Django 3.1.1 on 2020-10-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20201006_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'корзинка', 'verbose_name_plural': 'корзинки'},
        ),
    ]
