# Generated by Django 3.1.1 on 2020-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20201028_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PRD', 'обработан'), ('PD', 'оплачен'), ('RDY', 'готов'), ('DN', 'выполнен'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='Статус заказа'),
        ),
    ]
